### ISSUE TITLE
travis removal?

### ISSUE THREAD

**Issue by ghost** [nwolber/passgen#9]
since development has practically stopped on this project, is it even necessary to have travis enabled?

**Comment by nwolber** [comment]
Hm, whats the benefit in removing Travis integration?

**Comment by ghost** [comment]
@nwolber this isn't activly developed anymore, no need for travis

**Comment by nwolber** [comment]
I still see no real benefit in removing Travis.

**Comment by ghost** [comment]
@nwolber there's no benefit in keeping it if the project isn't being developed on anymore, travis is for logging changes of stable projects and this no longer a stable project
